### ISSUE TITLE
what SDR board are you using ?

### ISSUE THREAD

**Issue by gedw99** [fernandosanchezjr/gosdr#1]
this is crazy cool.

I was wondering what board your using.

There is a lot that can be done with GIO for building tooling and visualisation

**Comment by fernandosanchezjr** [comment]
I am using the NESDR SMART v4 and v5. In theory any RTL-SDR supported stick
should work - but you know how theory is.

**Comment by fernandosanchezjr** [comment]
By the way I am looking to invest some effort into building all the required UI controls for the tool in GIO - my goal is to go beyond a Hello World with the toolkit and find serious gains or pitfalls. But I must spend some more time learning about FIR filters and IQ sampling - as you can see in my wonky histogram.
